# Generated by Django 4.1.7 on 2023-03-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
