# Generated by Django 4.1.7 on 2023-03-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_driver_driver_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.IntegerField()),
                ('date', models.CharField(max_length=255)),
                ('vehicle', models.CharField(max_length=255)),
                ('shift', models.CharField(max_length=255)),
                ('waypoints', models.TextField()),
                ('summary', models.TextField()),
                ('route', models.TextField()),
            ],
            options={
                'db_table': 'customer_order',
                'managed': False,
            },
        ),
    ]
